name: CI/CD Pipeline for Docker Deployment

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 047719644852.dkr.ecr.us-east-1.amazonaws.com

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t myrepo .

      # Step 4: Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag myrepo:latest 047719644852.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest

      # Step 5: Push Docker image to AWS ECR
      - name: Push Docker Image to ECR
        run: |
          docker push 047719644852.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest

      # Step 6: Deploy to Lightsail EC2
      - name: Deploy to Ubuntu EC2
        env:
          LIGHTSAIL_KEY: ${{ secrets.EC2_PEM_FILE }}
        run: |
          echo "${{ secrets.EC2_PEM_FILE }}" > EC2_PEM_FILE.pem
          chmod 600 EC2_PEM_FILE.pem

          ssh -o StrictHostKeyChecking=no -i EC2_PEM_FILE.pem ubuntu@3.236.39.13 << 'EOF'
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 047719644852.dkr.ecr.us-east-1.amazonaws.com
            docker pull 047719644852.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 80:80 047719644852.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
          EOF
