name: CI/CD Pipeline for Docker Deployment

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 047719644852.dkr.ecr.us-east-1.amazonaws.com

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t myrepo .

      # Step 5: Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag myrepo:latest 047719644852.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest

      # Step 6: Push Docker image to AWS ECR
      - name: Push Docker Image to ECR
        run: |
          docker push 047719644852.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest

      # Step 7: Deploy to EC2 instance
      - name: Deploy to Ubuntu EC2
        env:
          LIGHTSAIL_KEY: ${{ secrets.EC2_PEM_FILE }}
        run: |
          # Save the private key to a file
          echo "${{ secrets.EC2_PEM_FILE }}" > EC2_PEM_FILE.pem
          chmod 600 EC2_PEM_FILE.pem

          # SSH into EC2 and deploy the image
          ssh -o StrictHostKeyChecking=no -i EC2_PEM_FILE.pem ubuntu@54.197.8.180 << 'EOF'
            # Log in to ECR on EC2
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 047719644852.dkr.ecr.us-east-1.amazonaws.com
            # Pull the Docker image from ECR
            docker pull 047719644852.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
            # Run the new container without any specific name
            docker run -d -p 80:80 047719644852.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
          EOF
